version: '3'
services:
  bdg-hive-metastore:
    ports:
      - 9083:9083
    image: timveil/docker-hadoop-hive-metastore:${D_METASTORE_VERSION}

  bdg-sequila:
    links:
      - bdg-hive-metastore
    environment:
      - "USERID=${D_UID}"
      - "GROUPID=${D_GID}"
    ports:
      -  10000:10000
      - 4040:4040
    depends_on:
      - bdg-hive-metastore
    image: biodatageeks/bdg-sequila:${D_SEQUILA_VERSION}
    volumes:
      - /Users/marek/data/bams/:${D_DATA}
    command: bdg-start-thriftserver --master=${D_SEQUILA_MASTER} --driver-memory=${D_SEQUILA_DRIVER_MEM} --conf spark.hadoop.hive.server2.authentication=NOSASL --conf  spark.hadoop.hive.metastore.uris=thrift://bdg-hive-metastore:9083 -v

  bdg-superset:
    ports:
      - 8088:8088
    links:
      - bdg-sequila
    depends_on:
      - bdg-sequila
    image: amancevice/superset:${D_SUPERSET_VERSION}





